require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AccomplishmentsController do

  def mock_accomplishment(stubs={})
    @mock_accomplishment ||= mock_model(Accomplishment, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all accomplishments as @accomplishments" do
      Accomplishment.stub(:all) { [mock_accomplishment] }
      get :index
      assigns(:accomplishments).should eq([mock_accomplishment])
    end
  end

  describe "GET show" do
    it "assigns the requested accomplishment as @accomplishment" do
      Accomplishment.stub(:find).with("37") { mock_accomplishment }
      get :show, :id => "37"
      assigns(:accomplishment).should be(mock_accomplishment)
    end
  end

  describe "GET new" do
    it "assigns a new accomplishment as @accomplishment" do
      Accomplishment.stub(:new) { mock_accomplishment }
      get :new
      assigns(:accomplishment).should be(mock_accomplishment)
    end
  end

  describe "GET edit" do
    it "assigns the requested accomplishment as @accomplishment" do
      Accomplishment.stub(:find).with("37") { mock_accomplishment }
      get :edit, :id => "37"
      assigns(:accomplishment).should be(mock_accomplishment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created accomplishment as @accomplishment" do
        Accomplishment.stub(:new).with({'these' => 'params'}) { mock_accomplishment(:save => true) }
        post :create, :accomplishment => {'these' => 'params'}
        assigns(:accomplishment).should be(mock_accomplishment)
      end

      it "redirects to the created accomplishment" do
        Accomplishment.stub(:new) { mock_accomplishment(:save => true) }
        post :create, :accomplishment => {}
        response.should redirect_to(accomplishment_url(mock_accomplishment))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved accomplishment as @accomplishment" do
        Accomplishment.stub(:new).with({'these' => 'params'}) { mock_accomplishment(:save => false) }
        post :create, :accomplishment => {'these' => 'params'}
        assigns(:accomplishment).should be(mock_accomplishment)
      end

      it "re-renders the 'new' template" do
        Accomplishment.stub(:new) { mock_accomplishment(:save => false) }
        post :create, :accomplishment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested accomplishment" do
        Accomplishment.stub(:find).with("37") { mock_accomplishment }
        mock_accomplishment.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :accomplishment => {'these' => 'params'}
      end

      it "assigns the requested accomplishment as @accomplishment" do
        Accomplishment.stub(:find) { mock_accomplishment(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:accomplishment).should be(mock_accomplishment)
      end

      it "redirects to the accomplishment" do
        Accomplishment.stub(:find) { mock_accomplishment(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(accomplishment_url(mock_accomplishment))
      end
    end

    describe "with invalid params" do
      it "assigns the accomplishment as @accomplishment" do
        Accomplishment.stub(:find) { mock_accomplishment(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:accomplishment).should be(mock_accomplishment)
      end

      it "re-renders the 'edit' template" do
        Accomplishment.stub(:find) { mock_accomplishment(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested accomplishment" do
      Accomplishment.stub(:find).with("37") { mock_accomplishment }
      mock_accomplishment.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the accomplishments list" do
      Accomplishment.stub(:find) { mock_accomplishment }
      delete :destroy, :id => "1"
      response.should redirect_to(accomplishments_url)
    end
  end

end
