require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CoverLettersController do

  def mock_cover_letter(stubs={})
    @mock_cover_letter ||= mock_model(CoverLetter, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cover_letters as @cover_letters" do
      CoverLetter.stub(:all) { [mock_cover_letter] }
      get :index
      assigns(:cover_letters).should eq([mock_cover_letter])
    end
  end

  describe "GET show" do
    it "assigns the requested cover_letter as @cover_letter" do
      CoverLetter.stub(:find).with("37") { mock_cover_letter }
      get :show, :id => "37"
      assigns(:cover_letter).should be(mock_cover_letter)
    end
  end

  describe "GET new" do
    it "assigns a new cover_letter as @cover_letter" do
      CoverLetter.stub(:new) { mock_cover_letter }
      get :new
      assigns(:cover_letter).should be(mock_cover_letter)
    end
  end

  describe "GET edit" do
    it "assigns the requested cover_letter as @cover_letter" do
      CoverLetter.stub(:find).with("37") { mock_cover_letter }
      get :edit, :id => "37"
      assigns(:cover_letter).should be(mock_cover_letter)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cover_letter as @cover_letter" do
        CoverLetter.stub(:new).with({'these' => 'params'}) { mock_cover_letter(:save => true) }
        post :create, :cover_letter => {'these' => 'params'}
        assigns(:cover_letter).should be(mock_cover_letter)
      end

      it "redirects to the created cover_letter" do
        CoverLetter.stub(:new) { mock_cover_letter(:save => true) }
        post :create, :cover_letter => {}
        response.should redirect_to(cover_letter_url(mock_cover_letter))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cover_letter as @cover_letter" do
        CoverLetter.stub(:new).with({'these' => 'params'}) { mock_cover_letter(:save => false) }
        post :create, :cover_letter => {'these' => 'params'}
        assigns(:cover_letter).should be(mock_cover_letter)
      end

      it "re-renders the 'new' template" do
        CoverLetter.stub(:new) { mock_cover_letter(:save => false) }
        post :create, :cover_letter => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cover_letter" do
        CoverLetter.stub(:find).with("37") { mock_cover_letter }
        mock_cover_letter.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cover_letter => {'these' => 'params'}
      end

      it "assigns the requested cover_letter as @cover_letter" do
        CoverLetter.stub(:find) { mock_cover_letter(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cover_letter).should be(mock_cover_letter)
      end

      it "redirects to the cover_letter" do
        CoverLetter.stub(:find) { mock_cover_letter(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cover_letter_url(mock_cover_letter))
      end
    end

    describe "with invalid params" do
      it "assigns the cover_letter as @cover_letter" do
        CoverLetter.stub(:find) { mock_cover_letter(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cover_letter).should be(mock_cover_letter)
      end

      it "re-renders the 'edit' template" do
        CoverLetter.stub(:find) { mock_cover_letter(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cover_letter" do
      CoverLetter.stub(:find).with("37") { mock_cover_letter }
      mock_cover_letter.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cover_letters list" do
      CoverLetter.stub(:find) { mock_cover_letter }
      delete :destroy, :id => "1"
      response.should redirect_to(cover_letters_url)
    end
  end

end
