require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe JobvertsController do

  def mock_jobvert(stubs={})
    @mock_jobvert ||= mock_model(Jobvert, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all jobverts as @jobverts" do
      Jobvert.stub(:all) { [mock_jobvert] }
      get :index
      assigns(:jobverts).should eq([mock_jobvert])
    end
  end

  describe "GET show" do
    it "assigns the requested jobvert as @jobvert" do
      Jobvert.stub(:find).with("37") { mock_jobvert }
      get :show, :id => "37"
      assigns(:jobvert).should be(mock_jobvert)
    end
  end

  describe "GET new" do
    it "assigns a new jobvert as @jobvert" do
      Jobvert.stub(:new) { mock_jobvert }
      get :new
      assigns(:jobvert).should be(mock_jobvert)
    end
  end

  describe "GET edit" do
    it "assigns the requested jobvert as @jobvert" do
      Jobvert.stub(:find).with("37") { mock_jobvert }
      get :edit, :id => "37"
      assigns(:jobvert).should be(mock_jobvert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created jobvert as @jobvert" do
        Jobvert.stub(:new).with({'these' => 'params'}) { mock_jobvert(:save => true) }
        post :create, :jobvert => {'these' => 'params'}
        assigns(:jobvert).should be(mock_jobvert)
      end

      it "redirects to the created jobvert" do
        Jobvert.stub(:new) { mock_jobvert(:save => true) }
        post :create, :jobvert => {}
        response.should redirect_to(jobvert_url(mock_jobvert))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jobvert as @jobvert" do
        Jobvert.stub(:new).with({'these' => 'params'}) { mock_jobvert(:save => false) }
        post :create, :jobvert => {'these' => 'params'}
        assigns(:jobvert).should be(mock_jobvert)
      end

      it "re-renders the 'new' template" do
        Jobvert.stub(:new) { mock_jobvert(:save => false) }
        post :create, :jobvert => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jobvert" do
        Jobvert.stub(:find).with("37") { mock_jobvert }
        mock_jobvert.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :jobvert => {'these' => 'params'}
      end

      it "assigns the requested jobvert as @jobvert" do
        Jobvert.stub(:find) { mock_jobvert(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:jobvert).should be(mock_jobvert)
      end

      it "redirects to the jobvert" do
        Jobvert.stub(:find) { mock_jobvert(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(jobvert_url(mock_jobvert))
      end
    end

    describe "with invalid params" do
      it "assigns the jobvert as @jobvert" do
        Jobvert.stub(:find) { mock_jobvert(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:jobvert).should be(mock_jobvert)
      end

      it "re-renders the 'edit' template" do
        Jobvert.stub(:find) { mock_jobvert(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jobvert" do
      Jobvert.stub(:find).with("37") { mock_jobvert }
      mock_jobvert.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the jobverts list" do
      Jobvert.stub(:find) { mock_jobvert }
      delete :destroy, :id => "1"
      response.should redirect_to(jobverts_url)
    end
  end

end
