require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PraisesController do

  def mock_praise(stubs={})
    @mock_praise ||= mock_model(Praise, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all praises as @praises" do
      Praise.stub(:all) { [mock_praise] }
      get :index
      assigns(:praises).should eq([mock_praise])
    end
  end

  describe "GET show" do
    it "assigns the requested praise as @praise" do
      Praise.stub(:find).with("37") { mock_praise }
      get :show, :id => "37"
      assigns(:praise).should be(mock_praise)
    end
  end

  describe "GET new" do
    it "assigns a new praise as @praise" do
      Praise.stub(:new) { mock_praise }
      get :new
      assigns(:praise).should be(mock_praise)
    end
  end

  describe "GET edit" do
    it "assigns the requested praise as @praise" do
      Praise.stub(:find).with("37") { mock_praise }
      get :edit, :id => "37"
      assigns(:praise).should be(mock_praise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created praise as @praise" do
        Praise.stub(:new).with({'these' => 'params'}) { mock_praise(:save => true) }
        post :create, :praise => {'these' => 'params'}
        assigns(:praise).should be(mock_praise)
      end

      it "redirects to the created praise" do
        Praise.stub(:new) { mock_praise(:save => true) }
        post :create, :praise => {}
        response.should redirect_to(praise_url(mock_praise))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved praise as @praise" do
        Praise.stub(:new).with({'these' => 'params'}) { mock_praise(:save => false) }
        post :create, :praise => {'these' => 'params'}
        assigns(:praise).should be(mock_praise)
      end

      it "re-renders the 'new' template" do
        Praise.stub(:new) { mock_praise(:save => false) }
        post :create, :praise => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested praise" do
        Praise.stub(:find).with("37") { mock_praise }
        mock_praise.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :praise => {'these' => 'params'}
      end

      it "assigns the requested praise as @praise" do
        Praise.stub(:find) { mock_praise(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:praise).should be(mock_praise)
      end

      it "redirects to the praise" do
        Praise.stub(:find) { mock_praise(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(praise_url(mock_praise))
      end
    end

    describe "with invalid params" do
      it "assigns the praise as @praise" do
        Praise.stub(:find) { mock_praise(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:praise).should be(mock_praise)
      end

      it "re-renders the 'edit' template" do
        Praise.stub(:find) { mock_praise(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested praise" do
      Praise.stub(:find).with("37") { mock_praise }
      mock_praise.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the praises list" do
      Praise.stub(:find) { mock_praise }
      delete :destroy, :id => "1"
      response.should redirect_to(praises_url)
    end
  end

end
