require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe RecommendationsController do

  def mock_recommendation(stubs={})
    @mock_recommendation ||= mock_model(Recommendation, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all recommendations as @recommendations" do
      Recommendation.stub(:all) { [mock_recommendation] }
      get :index
      assigns(:recommendations).should eq([mock_recommendation])
    end
  end

  describe "GET show" do
    it "assigns the requested recommendation as @recommendation" do
      Recommendation.stub(:find).with("37") { mock_recommendation }
      get :show, :id => "37"
      assigns(:recommendation).should be(mock_recommendation)
    end
  end

  describe "GET new" do
    it "assigns a new recommendation as @recommendation" do
      Recommendation.stub(:new) { mock_recommendation }
      get :new
      assigns(:recommendation).should be(mock_recommendation)
    end
  end

  describe "GET edit" do
    it "assigns the requested recommendation as @recommendation" do
      Recommendation.stub(:find).with("37") { mock_recommendation }
      get :edit, :id => "37"
      assigns(:recommendation).should be(mock_recommendation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created recommendation as @recommendation" do
        Recommendation.stub(:new).with({'these' => 'params'}) { mock_recommendation(:save => true) }
        post :create, :recommendation => {'these' => 'params'}
        assigns(:recommendation).should be(mock_recommendation)
      end

      it "redirects to the created recommendation" do
        Recommendation.stub(:new) { mock_recommendation(:save => true) }
        post :create, :recommendation => {}
        response.should redirect_to(recommendation_url(mock_recommendation))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recommendation as @recommendation" do
        Recommendation.stub(:new).with({'these' => 'params'}) { mock_recommendation(:save => false) }
        post :create, :recommendation => {'these' => 'params'}
        assigns(:recommendation).should be(mock_recommendation)
      end

      it "re-renders the 'new' template" do
        Recommendation.stub(:new) { mock_recommendation(:save => false) }
        post :create, :recommendation => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recommendation" do
        Recommendation.stub(:find).with("37") { mock_recommendation }
        mock_recommendation.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :recommendation => {'these' => 'params'}
      end

      it "assigns the requested recommendation as @recommendation" do
        Recommendation.stub(:find) { mock_recommendation(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:recommendation).should be(mock_recommendation)
      end

      it "redirects to the recommendation" do
        Recommendation.stub(:find) { mock_recommendation(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(recommendation_url(mock_recommendation))
      end
    end

    describe "with invalid params" do
      it "assigns the recommendation as @recommendation" do
        Recommendation.stub(:find) { mock_recommendation(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:recommendation).should be(mock_recommendation)
      end

      it "re-renders the 'edit' template" do
        Recommendation.stub(:find) { mock_recommendation(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recommendation" do
      Recommendation.stub(:find).with("37") { mock_recommendation }
      mock_recommendation.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the recommendations list" do
      Recommendation.stub(:find) { mock_recommendation }
      delete :destroy, :id => "1"
      response.should redirect_to(recommendations_url)
    end
  end

end
