require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ResponsibilitiesController do

  def mock_responsibility(stubs={})
    @mock_responsibility ||= mock_model(Responsibility, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all responsibilities as @responsibilities" do
      Responsibility.stub(:all) { [mock_responsibility] }
      get :index
      assigns(:responsibilities).should eq([mock_responsibility])
    end
  end

  describe "GET show" do
    it "assigns the requested responsibility as @responsibility" do
      Responsibility.stub(:find).with("37") { mock_responsibility }
      get :show, :id => "37"
      assigns(:responsibility).should be(mock_responsibility)
    end
  end

  describe "GET new" do
    it "assigns a new responsibility as @responsibility" do
      Responsibility.stub(:new) { mock_responsibility }
      get :new
      assigns(:responsibility).should be(mock_responsibility)
    end
  end

  describe "GET edit" do
    it "assigns the requested responsibility as @responsibility" do
      Responsibility.stub(:find).with("37") { mock_responsibility }
      get :edit, :id => "37"
      assigns(:responsibility).should be(mock_responsibility)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created responsibility as @responsibility" do
        Responsibility.stub(:new).with({'these' => 'params'}) { mock_responsibility(:save => true) }
        post :create, :responsibility => {'these' => 'params'}
        assigns(:responsibility).should be(mock_responsibility)
      end

      it "redirects to the created responsibility" do
        Responsibility.stub(:new) { mock_responsibility(:save => true) }
        post :create, :responsibility => {}
        response.should redirect_to(responsibility_url(mock_responsibility))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved responsibility as @responsibility" do
        Responsibility.stub(:new).with({'these' => 'params'}) { mock_responsibility(:save => false) }
        post :create, :responsibility => {'these' => 'params'}
        assigns(:responsibility).should be(mock_responsibility)
      end

      it "re-renders the 'new' template" do
        Responsibility.stub(:new) { mock_responsibility(:save => false) }
        post :create, :responsibility => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested responsibility" do
        Responsibility.stub(:find).with("37") { mock_responsibility }
        mock_responsibility.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :responsibility => {'these' => 'params'}
      end

      it "assigns the requested responsibility as @responsibility" do
        Responsibility.stub(:find) { mock_responsibility(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:responsibility).should be(mock_responsibility)
      end

      it "redirects to the responsibility" do
        Responsibility.stub(:find) { mock_responsibility(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(responsibility_url(mock_responsibility))
      end
    end

    describe "with invalid params" do
      it "assigns the responsibility as @responsibility" do
        Responsibility.stub(:find) { mock_responsibility(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:responsibility).should be(mock_responsibility)
      end

      it "re-renders the 'edit' template" do
        Responsibility.stub(:find) { mock_responsibility(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested responsibility" do
      Responsibility.stub(:find).with("37") { mock_responsibility }
      mock_responsibility.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the responsibilities list" do
      Responsibility.stub(:find) { mock_responsibility }
      delete :destroy, :id => "1"
      response.should redirect_to(responsibilities_url)
    end
  end

end
