require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TrophiesController do

  def mock_trophy(stubs={})
    @mock_trophy ||= mock_model(Trophy, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all trophies as @trophies" do
      Trophy.stub(:all) { [mock_trophy] }
      get :index
      assigns(:trophies).should eq([mock_trophy])
    end
  end

  describe "GET show" do
    it "assigns the requested trophy as @trophy" do
      Trophy.stub(:find).with("37") { mock_trophy }
      get :show, :id => "37"
      assigns(:trophy).should be(mock_trophy)
    end
  end

  describe "GET new" do
    it "assigns a new trophy as @trophy" do
      Trophy.stub(:new) { mock_trophy }
      get :new
      assigns(:trophy).should be(mock_trophy)
    end
  end

  describe "GET edit" do
    it "assigns the requested trophy as @trophy" do
      Trophy.stub(:find).with("37") { mock_trophy }
      get :edit, :id => "37"
      assigns(:trophy).should be(mock_trophy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created trophy as @trophy" do
        Trophy.stub(:new).with({'these' => 'params'}) { mock_trophy(:save => true) }
        post :create, :trophy => {'these' => 'params'}
        assigns(:trophy).should be(mock_trophy)
      end

      it "redirects to the created trophy" do
        Trophy.stub(:new) { mock_trophy(:save => true) }
        post :create, :trophy => {}
        response.should redirect_to(trophy_url(mock_trophy))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trophy as @trophy" do
        Trophy.stub(:new).with({'these' => 'params'}) { mock_trophy(:save => false) }
        post :create, :trophy => {'these' => 'params'}
        assigns(:trophy).should be(mock_trophy)
      end

      it "re-renders the 'new' template" do
        Trophy.stub(:new) { mock_trophy(:save => false) }
        post :create, :trophy => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trophy" do
        Trophy.stub(:find).with("37") { mock_trophy }
        mock_trophy.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :trophy => {'these' => 'params'}
      end

      it "assigns the requested trophy as @trophy" do
        Trophy.stub(:find) { mock_trophy(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:trophy).should be(mock_trophy)
      end

      it "redirects to the trophy" do
        Trophy.stub(:find) { mock_trophy(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(trophy_url(mock_trophy))
      end
    end

    describe "with invalid params" do
      it "assigns the trophy as @trophy" do
        Trophy.stub(:find) { mock_trophy(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:trophy).should be(mock_trophy)
      end

      it "re-renders the 'edit' template" do
        Trophy.stub(:find) { mock_trophy(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trophy" do
      Trophy.stub(:find).with("37") { mock_trophy }
      mock_trophy.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the trophies list" do
      Trophy.stub(:find) { mock_trophy }
      delete :destroy, :id => "1"
      response.should redirect_to(trophies_url)
    end
  end

end
