require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe WorkExperiencesController do

  def mock_work_experience(stubs={})
    @mock_work_experience ||= mock_model(WorkExperience, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all work_experiences as @work_experiences" do
      WorkExperience.stub(:all) { [mock_work_experience] }
      get :index
      assigns(:work_experiences).should eq([mock_work_experience])
    end
  end

  describe "GET show" do
    it "assigns the requested work_experience as @work_experience" do
      WorkExperience.stub(:find).with("37") { mock_work_experience }
      get :show, :id => "37"
      assigns(:work_experience).should be(mock_work_experience)
    end
  end

  describe "GET new" do
    it "assigns a new work_experience as @work_experience" do
      WorkExperience.stub(:new) { mock_work_experience }
      get :new
      assigns(:work_experience).should be(mock_work_experience)
    end
  end

  describe "GET edit" do
    it "assigns the requested work_experience as @work_experience" do
      WorkExperience.stub(:find).with("37") { mock_work_experience }
      get :edit, :id => "37"
      assigns(:work_experience).should be(mock_work_experience)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created work_experience as @work_experience" do
        WorkExperience.stub(:new).with({'these' => 'params'}) { mock_work_experience(:save => true) }
        post :create, :work_experience => {'these' => 'params'}
        assigns(:work_experience).should be(mock_work_experience)
      end

      it "redirects to the created work_experience" do
        WorkExperience.stub(:new) { mock_work_experience(:save => true) }
        post :create, :work_experience => {}
        response.should redirect_to(work_experience_url(mock_work_experience))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved work_experience as @work_experience" do
        WorkExperience.stub(:new).with({'these' => 'params'}) { mock_work_experience(:save => false) }
        post :create, :work_experience => {'these' => 'params'}
        assigns(:work_experience).should be(mock_work_experience)
      end

      it "re-renders the 'new' template" do
        WorkExperience.stub(:new) { mock_work_experience(:save => false) }
        post :create, :work_experience => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested work_experience" do
        WorkExperience.stub(:find).with("37") { mock_work_experience }
        mock_work_experience.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :work_experience => {'these' => 'params'}
      end

      it "assigns the requested work_experience as @work_experience" do
        WorkExperience.stub(:find) { mock_work_experience(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:work_experience).should be(mock_work_experience)
      end

      it "redirects to the work_experience" do
        WorkExperience.stub(:find) { mock_work_experience(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(work_experience_url(mock_work_experience))
      end
    end

    describe "with invalid params" do
      it "assigns the work_experience as @work_experience" do
        WorkExperience.stub(:find) { mock_work_experience(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:work_experience).should be(mock_work_experience)
      end

      it "re-renders the 'edit' template" do
        WorkExperience.stub(:find) { mock_work_experience(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested work_experience" do
      WorkExperience.stub(:find).with("37") { mock_work_experience }
      mock_work_experience.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the work_experiences list" do
      WorkExperience.stub(:find) { mock_work_experience }
      delete :destroy, :id => "1"
      response.should redirect_to(work_experiences_url)
    end
  end

end
